version: "3.7"

services:
  cinema:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dynamoDB
    networks:
      - cinema_network
    environment:
      - omdb_url=${OMDB_URL:-http://www.omdbapi.com}
      - movies=${MOVIES:-tt0232500,tt0322259,tt0463985,tt1013752,tt1596343,tt1905041,tt2820852,tt4630562}
      - api_key=${API_KEY}
      - movie_cache_timeout=${CACHE_TIMEOUT:-600}
      - dynamo_table=cinema
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy}
      - AWS_REGION=${AWS_REGION:-us-west2}
      - dynamodb_url=${DYNAMODB_ENDPOINT:-http://dynamodb:8000}

  dynamoDB:
    image: amazon/dynamodb-local
    container_name: ciema-db
    hostname: dynamodb
    restart: always
    ports:
      - "8000:8000"
    networks:
      - cinema_network
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name cinema --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb:8000"
    depends_on:
      - dynamoDB
    networks:
      - cinema_network
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1



networks:
  cinema_network: